name: Lint Code and Pre-commit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install poetry pre-commit
          poetry install

      - name: Run Pre-commit Hooks
        run: |
          pre-commit run --all-files
